name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Other -> Other/Integration
        if: github.base_ref != 'master'
        run: |
          echo "SUCCESS: Merging into this branch is allowed."
          exit 0
      -
        name: Check Integration -> Master
        if: github.base_ref == 'master' && github.head_ref == 'integration'
        run: |
          echo "SUCCESS: You are able to merge into the master branch from integration."
          exit 0
      -
        name: Check Other -> Master
        if: github.base_ref == 'master' && github.head_ref != 'integration'
        run: |
          echo "ERROR: You can only merge to master from integration."
          exit 1
