name: Docker Build CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build and Test
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false  # Only test the build process.
          tags: discord-tz-bot:latest
